### ISSUE TITLE
asymmetric strategies not generating entry signals if exit condition not yet met

### ISSUE THREAD

**Issue by bbac63** [shikokuchuo/ichimoku#9]
If I use a type 3 strategy at the end of the chart where the exit condition is not yet met, the entry condition is not triggered either. For type 1 strategies it works as expected. For testing purposes I used a quasi-symmetric type 3 strategy, but saw the same behaviour with real examples.

Here is the code for testing:
```
library(ichimoku)
library(quantmod)
library(dplyr)

# return xts object with daily data for Gold future for the current year;
# yahoo Symbol: "GC=F" and remove all rows with NA
xts_obj <- getSymbols("GC=F", auto.assign = FALSE, from = '2024-01-01', to = '2024-08-12') %>% na.omit()  

# calculate all inidcators for the Ichimoku cloud
cloud <- ichimoku(xts_obj)

# define the symetric strategy: tenkan > kijun 
strat_type_1 <- strat(cloud, c1 = "tenkan", c2 = "kijun", type = 1)

# entry signal generated on July 8
plot(strat_type_1)

# define similar asymetric strategy tenkan > kijun x kijun > tenkan
strat_type_3 <- strat(cloud, c1 = "tenkan", c2 = "kijun", c3 = "kijun", c4 = "tenkan", type = 3)

# entry signal not generated on July 8
plot(strat_type_3)
```

**Comment by shikokuchuo** [comment]
@bbac63 thanks for reporting. Can you confirm that [c52fcf9](https://github.com/shikokuchuo/ichimoku/commit/c52fcf913a9d460e3cd9a2fc513de941a4977eaf) indeed fixes the issue for you?

**Comment by bbac63** [comment]
Thank you @shikokuchuo: The issue is fixed.
